development:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: killbills_development
  pool: 5

test:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: killbills_test
  pool: 5
